version: "3"
services:
  app:
    image: tehwey/feedbridge:latest
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=prod
      - REFRESH_INTERVAL=15
      - STORAGE_BACKEND=persistent
      - STORAGE_PATH=/feedbridge-data
    volumes:
     - /home/dewey/services/feedbridge/feedbridge-data:/feedbridge-data
