version: "3"
services:
  app:
    image: tehwey/feedbridge:latest
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=prod
      - REFRESH_INTERVAL=15
      - CACHE_EXPIRATION=30
      - CACHE_EXPIRED_PURGE=60
      - STORAGE_BACKEND=memory
