{
 "title": "Feedbridge",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "# Feedbridge\n\nMetrics operated from Feedbridge running on https://feedbridge.notmyhostna.me."
  },
  {
   "title": "Average scrape duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "fb_runner_scrape_duration_seconds_sum / fb_runner_scrape_duration_seconds_count",
     "legendFormat": "{{plugin}}"
    }
   ]
  },
  {
   "title": "Scraped item count",
   "type": "graph",
   "description": "Scraped items on each scrape run.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "Items" }
   ],
   "targets": [
    { "expr": "fb_runner_items_scraped", "legendFormat": "{{plugin}}" }
   ]
  },
  {
   "title": "HTTP request rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code)(rate(http_requests_total[5m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Running goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"feedbridge\"}",
     "legendFormat": "{{go_goroutines}}"
    }
   ]
  }
 ]
}